config_version = 1

[audio]
enable_overdrive = true

[backdrop]
enabled = true

[bar.default]
background_opacity = 0.4999999888241291
margin_edge = 0
margin_ends = 0
radius = 0
radius_bottom_left = 0
radius_bottom_right = 0
radius_top_left = 0
radius_top_right = 0

[dock]
radius = 4

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[niri.backdrop]

[plugins]
enabled = []

[shell]
font_family = "LXGW WenKai Medium"
niri_overview_type_to_launch_enabled = true
polkit_agent = true
telemetry_enabled = true

    [shell.panel]
    transparency_mode = "glass"

[theme]
builtin = "Ayu"
community_palette = "Oxocarbon"
custom_palette = "1-mc"
mode = "light"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri", "qt" ]

[wallpaper.default]
path = "/home/xiaot_evo/Pictures/Wallpapers/1.png"

[wallpaper.last]
path = "/home/xiaot_evo/Pictures/Wallpapers/1.png"

[wallpaper.monitors.eDP-1]
path = "/home/xiaot_evo/Pictures/Wallpapers/1.png"

[widget.cat]
type = "noctalia/bongocat:cat"
